export default {
  /* header --start */
  'Header.home': 'Home',
  'Header.logout': 'Log out',
  'Header.changePwd': 'change password',
  'pleaseInput': 'Please Input',
  'pleaseSelect': 'Please Select',
  /* header --end */

  /* login --start */
  'Login.Title': 'Jiuhuar',
  'Login.company': 'Purchase Order Stystem',
  'Login.systemName': 'Log into PO System',
  'Login.login': 'Log In',
  'Login.usernamePlaceholder': 'Please Input the Username',
  'Login.emptyUsername': 'Username can not be empty',
  'Login.usernameWarningMes': 'Username should be a right email',
  'Login.passwordPlaceholder': 'Please Input the Password',
  'Login.emptyPassword': 'Password can not be empty',
  'Login.passwordWarningMes': 'Incorrect password format',
  'Login.formWarningMes': 'Form got error, please check',
  'Login.loginSuccess': 'Log In Success',
  'Login.autoLogin': 'Auto Login In 3 days',
  /* login --end */

  /* change password --start*/
  'ChangePwd.changePwd': 'Change Password',
  'ChangePwd.changePwdSuccess': 'change password success',
  'ChangePwd.formWarningMes': 'Form got error, please check',
  'ChangePwd.newPwdSameAsOldPwd': 'new password sholud not same as old password',
  'ChangePwd.confirmPwdNotSameAsnewPwd': 'comfirm Password not same as new password',
  'ChangePwd.changePasswordTips': 'Need to change the password after sign up',
  'ChangePwd.oldPwd': 'Old Password',
  'ChangePwd.newPwd': 'New Password',
  'ChangePwd.confirmPwd': 'Confirm Password',
  'ChangePwd.emptyPassword': 'Password can not be empty',
  'ChangePwd.oldPwdPlaceholder': 'please input the Old Password',
  'ChangePwd.newPwdPlaceholder': 'please input the New Password',
  'ChangePwd.confirmPwdPlaceholder': 'input the New Password Again',
  'ChangePwd.passwordWarningMes': 'Incorrect password format',
  'ChangePwd.save': 'Save',
  /* change password --end*/

  /* goods lists --start*/
  'GoodsList.filterTags': 'Filter Tags',
  'GoodsList.createGoods': 'Create Goods',
  'GoodsList.searchPlaceholder': 'Please Input the Search Content',
  'GoodsList.goods': 'Goods',
  'GoodsList.tags': 'Tags',
  'GoodsList.price': 'SR Price',
  'GoodsList.createTime': 'Create Time',
  'GoodsList.operation': 'Operation',
  'GoodsList.view': 'View',
  'GoodsList.edit': 'Edit',
  /* goods lists --end*/

  /* PurchaseSuppliers lists --start*/
  'PurchaseSuppliers.createSupplier': 'Create Supplier',
  'PurchaseSuppliers.searchPlaceholder': 'Please Input the Search Content',
  'PurchaseSuppliers.name': 'Supplier Name',
  'PurchaseSuppliers.shortName': 'Short Name',
  'PurchaseSuppliers.contactName': 'Contact Name',
  'PurchaseSuppliers.tel': 'Tel',
  'PurchaseSuppliers.POSITION': 'Position',
  'PurchaseSuppliers.Email': 'Email',
  'PurchaseSuppliers.operation': 'Operation',
  'PurchaseSuppliers.view': 'View',
  'PurchaseSuppliers.edit': 'Edit',
  'PurchaseSuppliers.createSuccess': 'Create Supplier Success',
  'PurchaseSuppliers.EditSuccess': 'Edit Supplier Success',
  'PurchaseSuppliers.AllWareHouse': 'All',
  /* PurchaseSuppliers lists --end*/

  /* AddSupplierModal --start*/
  'AddSupplierModal.createSupplier': 'Add Supplier',
  'AddSupplierModal.editSupplier': 'Edit Supplier',
  'AddSupplierModal.save': 'Save',
  'AddSupplierModal.cancel': 'Cancel',
  'AddSupplierModal.supplierInfo': 'Supplier Info',
  'AddSupplierModal.name': 'Supplier Name',
  'AddSupplierModal.inputName': 'Please input Supplier Name',
  'AddSupplierModal.shortName': 'Short Name',
  'AddSupplierModal.shortNameFormat': 'Wrong Short Name Format',
  'AddSupplierModal.inputShortName': 'Please input Supplier Short Name',
  'AddSupplierModal.address': 'Detail Address',
  'AddSupplierModal.contactInfo': 'Contact Info',
  'AddSupplierModal.email': 'Contact Email',
  'AddSupplierModal.emailFormat': 'Wrong Email Format',
  'AddSupplierModal.inputEmail': 'Please input Contact Email',
  'AddSupplierModal.contactName': 'Contact Name',
  'AddSupplierModal.tel': 'Contact Tel',
  'AddSupplierModal.position': 'Contact Duty',
  'AddSupplierModal.addContact': 'Add Contact',
  'AddSupplierModal.otherInfo': 'Other Info',
  /* AddSupplierModal --end*/

  /* CreateGoods --start*/
  'CreateGoods.goodsInfo': 'Goods Info',
  'CreateGoods.enProductName': 'English Commodity',
  'CreateGoods.enBrandName': 'English Branch',
  'CreateGoods.enName': 'English Name',
  'CreateGoods.enProductNameRequire': 'Please Input the English Commodity',
  'CreateGoods.enBrandNameRequire': 'Please Input the English Branch',
  'CreateGoods.enNameRequire': 'Please Input the English Name',
  'CreateGoods.goodsPic': 'Goods Main Pic',
  'CreateGoods.goodsPicRequire': 'Please Upload the Goods Main Pic ',

  'CreateGoods.cnName': 'Chinese Name',
  'CreateGoods.cnBrandName': 'Chinese Branch',
  'CreateGoods.cnProductName': 'Chinese Commodity',
  'CreateGoods.beerId': 'Encipher',
  'CreateGoods.currency': 'Settlement Currency',
  'CreateGoods.styleId': 'Style Type',
  'CreateGoods.specId': 'Specification Type',

  'CreateGoods.packType': 'Packaged Form',
  'CreateGoods.weight': 'Gross Weight (g)',
  'CreateGoods.categoryId': 'Goods Category',
  'CreateGoods.tagIds': 'Goods Tags',
  'CreateGoods.ratings': 'Goods Grade',
  'CreateGoods.lessThanThree': 'Less than 3 grade',
  'CreateGoods.jiuhuar': 'Jiuhuar',

  'CreateGoods.skuInfo': 'SKU Info',
  'CreateGoods.skuName': 'Sku Name',
  'CreateGoods.barCode': 'Sku Code',
  'CreateGoods.setSkusAttr': 'Set Skus Attribution',
  'CreateGoods.price': 'SR Price',
  'CreateGoods.supplierRequired': 'Please select a supplier',
  'CreateGoods.ratingRequired': 'Please input the rate',
  'CreateGoods.editGoodsSuccess': 'Edit Goods Success',
  'CreateGoods.createGoodsSuccess': 'Create Goods Success',
  'CreateGoods.save': 'Save',
  /* CreateGoods --end*/

  /* POList --start */
  'POList.code': 'Code',
  'POList.supplier': 'supplier',
  'POList.amount': 'amount',
  'POList.count': 'count',
  'POList.createTime': 'createTime',
  'POList.respository': 'respository',
  'POList.status': 'status',
  'POList.allIn': 'All in storage',
  'POList.partIn': 'Part in storage',
  'POList.waitIn': 'Wait in storage',
  'POList.operation': 'Operation',
  'POList.edit': 'Edit',
  'POList.view': 'View',
  'POList.confirm': 'Be sure to delete',
  'POList.yes': 'Confirm',
  'POList.no': 'Cancel',
  'POList.delete': 'Delete',
  'POList.sendEmail': 'Send Email',
  'POList.inStorage': 'In Storage',
  'POList.detail': 'Detail',
  'POList.all': 'All',
  'POList.addPO': 'Add New PO',
  'POList.allRepo': 'All repo',
  'POList.keyword': 'Please Input',
  'POList.allWareHouse': 'All',
  /* POList --end */

  /* Add new PO --start */
  'AddNewPO.orderNumber': 'Order Number',
  'AddNewPO.supplierId': 'Supplier',
  'AddNewPO.remark': 'Remark',
  'AddNewPO.addSupplier': 'Add Supplier',
  'AddNewPO.supplierRequired': 'Please select a Supplier',
  'AddNewPO.remarkPlaceholder': 'Please input Remark',

  'AddNewPO.purchaseGoods': 'Purchase Goods',
  'AddNewPO.addGoods': 'Add Goods',
  'AddNewPO.Repo': 'Repo',
  'AddNewPO.purchaseSumQuantity': 'Sum Quantity',
  'AddNewPO.purchaseSumPrice': 'Sum Price',

  'AddNewPO.goods': 'Goods',
  'AddNewPO.skuName': 'Goods sku',
  'AddNewPO.skuCode': 'Sku Code',
  'AddNewPO.price': 'Price',
  'AddNewPO.quantity': 'Quantity',
  'AddNewPO.sumPrice': 'Sum Price',
  'AddNewPO.operation': 'Operation',
  'AddNewPO.delete': 'Delete',
  'AddNewPO.priceReqiured': 'Price required',
  'AddNewPO.quantityReqiured': 'Quantity required',
  'AddNewPO.skuSelectReqiured': 'Select at least one item',
  'AddNewPO.editSuccess': 'PO Edit Success',
  'AddNewPO.createSuccess': 'PO Create Success',
  'AddNewPO.saveAndSendEmail': 'Save and Send Email',
  'AddNewPO.save': 'Save',
  'AddNewPO.cancel': 'Cancel',
  'AddNewPO.orderStatus': 'Status',
  'AddNewPO.backtoPre': 'Back to Pre',
  /* Add new PO --end */

  /* AddGoodsModal --start */
  'AddGoodsModal.goods': 'Goods',
  'AddGoodsModal.skuName': 'Goods sku',
  'AddGoodsModal.noSku': 'No Sku',
  'AddGoodsModal.barCode': 'Sku Code',
  'AddGoodsModal.status': 'Status',

  'AddGoodsModal.addGoods': 'Add Goods',
  'AddGoodsModal.confirm': 'Confirm',
  'AddGoodsModal.cancel': 'Cancel',
  'AddGoodsModal.repo': 'Repo',
  'AddGoodsModal.total': 'Total',
  'AddGoodsModal.many': 'goods',
  /* AddGoodsModal --end */

  /* SendEmailModal --start */
  'SendEmailModal.sendEmail': 'Send Email',
  'SendEmailModal.send': 'Send',
  'SendEmailModal.cancel': 'Cancel',
  'SendEmailModal.reciever': 'Reciever',
  'SendEmailModal.receiverRequired': 'Please select one reciever at least',
  'SendEmailModal.mainTopic': 'Main Topic',
  'SendEmailModal.content': 'Content',
  'SendEmailModal.annex': 'Annex',
  'SendEmailModal.sendSuccess': 'Send Success',
  'SendEmailModal.preview': 'Preview',
  /* SendEmailModal --end */

  /* InStorage --start */
  'InStorage.inStorageList': 'In Storage List',
  'InStorage.goods': 'Goods',
  'InStorage.skuName': 'SKU Name',
  'InStorage.quantity': 'Quantity',
  'InStorage.entryWarehouseQty': 'Entry Quantity',
  'InStorage.psNumber': 'Prepare storage number',
  'InStorage.productionDate': 'Production Date',
  'InStorage.locationNo': 'Location No',
  'InStorage.advanceSaleSetting': 'Advance Setting',
  'InStorage.advanceSale': 'Advance Sale',
  'InStorage.advanceSaleDay': 'Advance Sale Day',
  'InStorage.advanceSaleQty': 'Advance Sale Quantity',
  'InStorage.receiveTime': 'Receive Time',
  'InStorage.confirmIn': 'Confirm',
  'InStorage.cancel': 'Cancel',
  'InStorage.inStorageSuccess': 'Goods In storage Success',
  'InStorage.exceedingMaximum': 'Exceeding the maximum',
  'InStorage.selectedInstorageGoods': 'Please in storage one goods at least',
  /* InStorage --end */

  /* WarehouseInventory --start*/
  'WarehouseInventory.keyword': 'search product name or sku code',
  'WarehouseInventory.product': 'product',
  'WarehouseInventory.skuInfo': 'SKU info',
  'WarehouseInventory.noSku': 'no SKU',
  'WarehouseInventory.skuCode': 'SKU code',
  'WarehouseInventory.warehouse': 'warehouse',
  'WarehouseInventory.inventory': 'inventory',
  'WarehouseInventory.defaultWarehouse': 'all warehouse',
  /* WarehouseInventory --end */

  /* AddNewOutbound --start */
  'AddNewOutbound.outWarehouseNo': 'Outbound No',
  'AddNewOutbound.outboundTime': 'Outbound Time',
  'AddNewOutbound.remark': 'Remark',
  'AddNewOutbound.remarkPlaceholder': 'Please input Remark',

  'AddNewOutbound.outboundGoods': 'Outbound Goods',
  'AddNewOutbound.addGoods': 'Add Goods',
  'AddNewOutbound.Repo': 'Repo',
  'AddNewOutbound.purchaseSumQuantity': 'Sum Quantity',
  'AddNewOutbound.goodsWeight': 'Goods Weight (KG)',

  'AddNewOutbound.goods': 'Goods',
  'AddNewOutbound.skuName': 'Goods sku',
  'AddNewOutbound.skuCode': 'Sku Code',
  'AddNewOutbound.quantity': 'Quantity',
  'AddNewOutbound.outboundNumber': 'Outbound Number',
  'AddNewOutbound.operation': 'Operation',
  'AddNewOutbound.delete': 'Delete',
  'AddNewOutbound.quantityReqiured': 'Quantity required',
  'AddNewOutbound.skuSelectReqiured': 'Select at least one item',
  'AddNewOutbound.createSuccess': 'Outbound Create Success',
  'AddNewOutbound.save': 'Save',
  'AddNewOutbound.cancel': 'Cancel',
  'AddNewOutbound.backtoPre': 'Back to Pre',
  'AddNewOutbound.quantityUpdate': 'Goods Quantity Update',
  /* AddNewOutbound --end */

  /* GoodsOutbound --start */
  'GoodsOutbound.outWarehouseNo': 'Outbound No',
  'GoodsOutbound.outWarehouseNoRequired': 'Please input Outbound No',
  'GoodsOutbound.outboundTime': 'Time',
  'GoodsOutbound.createTime': 'Outbound Time',
  'GoodsOutbound.warehouse': 'Repo',
  'GoodsOutbound.outboundQuantity': 'Quantity',
  'GoodsOutbound.remark': 'Remark',
  'GoodsOutbound.operation': 'Operation',
  'GoodsOutbound.detail': 'detail',
  'GoodsOutbound.selectWarehouse': 'Select Warehouse',
  'GoodsOutbound.confirm': 'Confirm',
  'GoodsOutbound.cancel': 'Cancel',
  'GoodsOutbound.addOutbound': 'Add Outbound',
  /* GoodsOutbound --end */

  /* AddNewStockCount --start */
  'AddNewStockCount.verificationNo': 'Verification No',
  'AddNewStockCount.inventoryTime': 'Inventory Time',
  'AddNewStockCount.remark': 'Remark',
  'AddNewStockCount.status': 'Status',
  'AddNewStockCount.counted': 'Counted',
  'AddNewStockCount.notCounted': 'Not Counted',
  'AddNewStockCount.remarkPlaceholder': 'Please input Remark',
  'AddNewStockCount.noRemark': 'No Remark',

  'AddNewStockCount.outboundGoods': 'Stock Count Goods',
  'AddNewStockCount.addGoods': 'Add Goods',
  'AddNewStockCount.Repo': 'Repo',
  'AddNewStockCount.bookTotal': 'Book Total',
  'AddNewStockCount.actualTotal': 'Actual Total',

  'AddNewStockCount.goods': 'Goods',
  'AddNewStockCount.skuName': 'Goods sku',
  'AddNewStockCount.PONumber': 'Purchase Order No',
  'AddNewStockCount.inventory': 'Carrying Stock',
  'AddNewStockCount.locationNo': 'Location Encoding',
  'AddNewStockCount.noLocationNo': 'NO Location Encoding',
  'AddNewStockCount.inventoryProfitAndLoss': 'Profit and Loss',
  'AddNewStockCount.operation': 'Operation',
  'AddNewStockCount.delete': 'Delete',
  'AddNewStockCount.quantityReqiured': 'Quantity required',
  'AddNewStockCount.skuSelectReqiured': 'Select at least one item',
  'AddNewStockCount.createSuccess': 'Stock Count Create Success',
  'AddNewStockCount.inventorySuccess': 'Inventory Success',
  'AddNewStockCount.save': 'Save',
  'AddNewStockCount.cancel': 'Cancel',
  'AddNewStockCount.backtoPre': 'Back to Pre',
  /* AddNewOutbound --end */

  /* StockCount --start */
  'StockCount.verificationNo': 'Verification No',
  'StockCount.verificationNoRequired': 'Please input Verification No',
  'StockCount.inventoryTime': 'Time',
  'StockCount.createTime': 'Inventory Time',
  'StockCount.warehouse': 'Repo',
  'StockCount.bookTotal': 'Book Total',
  'StockCount.actualTotal': 'Actual Total',
  'StockCount.remark': 'Remark',
  'StockCount.counted': 'Counted',
  'StockCount.notCounted': 'Not Counted',
  'StockCount.status': 'Status',
  'StockCount.operation': 'Operation',
  'StockCount.detail': 'Detail',
  'StockCount.inventory': 'Inventery',
  'StockCount.selectWarehouse': 'Select Warehouse',
  'StockCount.confirm': 'Confirm',
  'StockCount.cancel': 'Cancel',
  'StockCount.countTime': 'Inventery Time',
  'StockCount.addStockCount': 'Add Inventery',
  /* StockCount --end */

  /* RichEditor --start */
  'RichEditor.previewArea': 'Preview Area',
  'RichEditor.goodsInfoPlace': 'Please Input Goods Info',
  'RichEditor.insertImage': 'Insert Image',
  'RichEditor.title': 'Title',
  'RichEditor.content': 'Content',
  'RichEditor.uploadImage': 'Upload Image',
  /* RichEditor --end */
}
