export default {
  /* header --start */
  'Header.home': '首页',
  'Header.logout': '退出',
  'Header.changePwd': '修改密码',
  'pleaseInput': '请输入',
  'pleaseSelect': '请选择',
  /* header --end */

  /* login --start */
  'Login.Title': '酒花儿',
  'Login.company': '采购管理系统',
  'Login.systemName': '账号登录',
  'Login.login': '登录',
  'Login.usernamePlaceholder': '请输入用户名',
  'Login.emptyUsername': '用户名不能为空',
  'Login.usernameWarningMes': '用户名需为正确的邮箱格式',
  'Login.passwordPlaceholder': '请输入密码',
  'Login.emptyPassword': '密码不能为空',
  'Login.passwordWarningMes': '请输入8位有效密码',
  'Login.formWarningMes': '表单填写有误，请仔细检查表单',
  'Login.loginSuccess': '登录成功',
  'Login.autoLogin': '三天内自动登录',
  /* login --end */

  /* change password --start*/
  'ChangePwd.changePwd': '密码修改',
  'ChangePwd.changePwdSuccess': '密码修改成功',
  'ChangePwd.formWarningMes': '表单填写有误，请仔细检查表单',
  'ChangePwd.newPwdSameAsOldPwd': '新密码不能和旧密码一样',
  'ChangePwd.confirmPwdNotSameAsnewPwd': '新密码两次填写不一致',
  'ChangePwd.changePasswordTips': '首次登陆需要重置登录密码',
  'ChangePwd.oldPwd': '原密码',
  'ChangePwd.newPwd': '新密码',
  'ChangePwd.confirmPwd': '确认新密码',
  'ChangePwd.emptyPassword': '密码不能为空',
  'ChangePwd.oldPwdPlaceholder': '请输入原密码',
  'ChangePwd.newPwdPlaceholder': '请输入新密码',
  'ChangePwd.confirmPwdPlaceholder': '请再次填写新密码',
  'ChangePwd.passwordWarningMes': '请输入8位有效密码',
  'ChangePwd.save': '保存',
  /* change password --end*/

  /* goods lists --start*/
  'GoodsList.filterTags': '筛选标签',
  'GoodsList.createGoods': '创建商品',
  'GoodsList.searchPlaceholder': '请输入搜索内容',
  'GoodsList.goods': '商品',
  'GoodsList.tags': '标签',
  'GoodsList.price': '建议零售价',
  'GoodsList.createTime': '创建时间',
  'GoodsList.operation': '操作',
  'GoodsList.view': '查看',
  'GoodsList.edit': '编辑',
  /* goods lists --end*/

  /* PurchaseSuppliers lists --start*/
  'PurchaseSuppliers.createSupplier': '新增供应商',
  'PurchaseSuppliers.searchPlaceholder': '请输入搜索内容',
  'PurchaseSuppliers.name': '供应商',
  'PurchaseSuppliers.shortName': '供应商简称',
  'PurchaseSuppliers.contactName': '联系人',
  'PurchaseSuppliers.tel': '联系方式',
  'PurchaseSuppliers.POSITION': '职务',
  'PurchaseSuppliers.Email': '邮箱',
  'PurchaseSuppliers.operation': '操作',
  'PurchaseSuppliers.view': '查看',
  'PurchaseSuppliers.edit': '编辑',
  'PurchaseSuppliers.createSuccess': '创建供应商成功',
  'PurchaseSuppliers.EditSuccess': '编辑供应商成功',
  'PurchaseSuppliers.AllWareHouse': '全部',
  /* PurchaseSuppliers lists --end*/

  /* AddSupplierModal --start*/
  'AddSupplierModal.createSupplier': '新增供应商',
  'AddSupplierModal.editSupplier': '编辑供应商',
  'AddSupplierModal.save': '保存',
  'AddSupplierModal.cancel': '取消',
  'AddSupplierModal.supplierInfo': '供应商信息',
  'AddSupplierModal.name': '供应商全称',
  'AddSupplierModal.inputName': '请填写供应商全称',
  'AddSupplierModal.shortName': '供应商简称',
  'AddSupplierModal.shortNameFormat': '简称只能为大写英文字母和数字',
  'AddSupplierModal.inputShortName': '请填写供应商简称',
  'AddSupplierModal.address': '详细地址',
  'AddSupplierModal.contactInfo': '联系人信息',
  'AddSupplierModal.email': '联系人邮箱',
  'AddSupplierModal.emailFormat': '错误的邮箱格式',
  'AddSupplierModal.inputEmail': '请填写联系人邮箱',
  'AddSupplierModal.contactName': '联系人姓名',
  'AddSupplierModal.tel': '联系人电话',
  'AddSupplierModal.position': '联系人职务',
  'AddSupplierModal.addContact': '添加联系人',
  'AddSupplierModal.otherInfo': '其他信息',
  'AddSupplierModal.confirm': '确认',
  /* AddSupplierModal --end*/

  /* CreateGoods --start*/
  'CreateGoods.goodsInfo': '商品信息',
  'CreateGoods.enProductName': '英文品名',
  'CreateGoods.enBrandName': '英文品牌',
  'CreateGoods.enName': '英文名称',
  'CreateGoods.enProductNameRequire': '请输入英文品名',
  'CreateGoods.enBrandNameRequire': '请输入英文品牌',
  'CreateGoods.enNameRequire': '请输入英文名称',
  'CreateGoods.goodsPic': '商品主图',
  'CreateGoods.goodsPicRequire': '请上传商品主图',

  'CreateGoods.cnName': '中文名称',
  'CreateGoods.cnBrandName': '中文品牌',
  'CreateGoods.cnProductName': '中文品名',
  'CreateGoods.beerId': '酒花编码',
  'CreateGoods.currency': '结算币种',
  'CreateGoods.styleId': '风格类型',
  'CreateGoods.specId': '规格类型',

  'CreateGoods.packType': '包装形式',
  'CreateGoods.weight': '商品毛重 (g)',
  'CreateGoods.categoryId': '商品分类',
  'CreateGoods.tagIds': '商品标签',
  'CreateGoods.ratings': '商品评分',
  'CreateGoods.lessThanThree': '最多只能勾选 3个评分',
  'CreateGoods.jiuhuar': '酒花儿',

  'CreateGoods.skuInfo': '规格信息',
  'CreateGoods.skuName': 'Sku 名称',
  'CreateGoods.barCode': 'Sku 编码',
  'CreateGoods.setSkusAttr': '请设置商品规格属性',
  'CreateGoods.price': '建议零售价',
  'CreateGoods.supplierRequired': '请选择供应商',
  'CreateGoods.ratingRequired': '请填写评分',
  'CreateGoods.editGoodsSuccess': '商品编辑成功',
  'CreateGoods.createGoodsSuccess': '商品编辑成功',
  'CreateGoods.save': '保存',
  /* CreateGoods --end*/

  /* POList --start */
  'POList.code': '采购单号',
  'POList.supplier': '供应商名称',
  'POList.amount': '采购总数',
  'POList.count': '采购总额',
  'POList.createTime': '创建时间',
  'POList.respository': '所属仓库',
  'POList.status': '状态',
  'POList.allIn': '全部入库',
  'POList.partIn': '部分入库',
  'POList.waitIn': '待入库',
  'POList.operation': '操作',
  'POList.edit': '编辑',
  'POList.view': '查看',
  'POList.confirm': '确定要删除？',
  'POList.yes': '确定',
  'POList.no': '取消',
  'POList.delete': '删除',
  'POList.sendEmail': '发送邮件',
  'POList.inStorage': '入库',
  'POList.detail': '详情',
  'POList.all': '全部',
  'POList.addPO': '新增采购订单',
  'POList.allRepo': '全部仓库',
  'POList.keyword': '请输入搜索内容',
  'POList.allWareHouse': '全部',
  /* POList --end */

  /* Add new PO --start */
  'AddNewPO.orderNumber': '采购订单',
  'AddNewPO.supplierId': '供应商',
  'AddNewPO.remark': '备注',
  'AddNewPO.addSupplier': '添加供应商',
  'AddNewPO.supplierRequired': '请选择供应商',
  'AddNewPO.remarkPlaceholder': '请输入留言',

  'AddNewPO.purchaseGoods': '采购商品',
  'AddNewPO.addGoods': '添加商品',
  'AddNewPO.Repo': '所属仓库',
  'AddNewPO.purchaseSumQuantity': '采购总数',
  'AddNewPO.purchaseSumPrice': '采购总额',

  'AddNewPO.goods': '商品',
  'AddNewPO.skuName': '商品规格',
  'AddNewPO.skuCode': 'SKU编码',
  'AddNewPO.quantity': '采购数量',
  'AddNewPO.price': '采购单价',
  'AddNewPO.sumPrice': '采购合计',
  'AddNewPO.operation': '操作',
  'AddNewPO.delete': '删除',
  'AddNewPO.priceReqiured': '请填写价格',
  'AddNewPO.quantityReqiured': '请填写数量',
  'AddNewPO.skuSelectReqiured': '请至少选择一个商品',
  'AddNewPO.editSuccess': '采购订单编辑成功',
  'AddNewPO.createSuccess': '采购订单创建成功',
  'AddNewPO.saveAndSendEmail': '保存并发送',
  'AddNewPO.save': '保存',
  'AddNewPO.cancel': '取消',
  'AddNewPO.orderStatus': '订单状态',
  'AddNewPO.backtoPre': '返回上一页',
  /* Add new PO --end */

  /* AddGoodsModal --start */
  'AddGoodsModal.goods': '商品',
  'AddGoodsModal.skuName': '商品规格',
  'AddGoodsModal.noSku': '无规格',
  'AddGoodsModal.barCode': 'SKU 编码',
  'AddGoodsModal.status': '状态',

  'AddGoodsModal.addGoods': '添加商品',
  'AddGoodsModal.confirm': '确定',
  'AddGoodsModal.cancel': '取消',
  'AddGoodsModal.repo': '所属仓库',
  'AddGoodsModal.total': '共',
  'AddGoodsModal.many': '件商品',
  /* AddGoodsModal --end */

  /* SendEmailModal --start */
  'SendEmailModal.sendEmail': '发功邮件',
  'SendEmailModal.send': '发送',
  'SendEmailModal.cancel': '取消',
  'SendEmailModal.reciever': '收件人',
  'SendEmailModal.receiverRequired': '请填写收件人',
  'SendEmailModal.mainTopic': '主题',
  'SendEmailModal.content': '内容',
  'SendEmailModal.annex': '附件',
  'SendEmailModal.sendSuccess': '邮件发送成功',
  'SendEmailModal.preview': '预览',
  /* SendEmailModal --end */

  /* InStorage --start */
  'InStorage.inStorageList': '入库商品清单',
  'InStorage.goods': '商品',
  'InStorage.skuName': '商品规格',
  'InStorage.quantity': '采购数量',
  'InStorage.entryWarehouseQty': '已入库数',
  'InStorage.psNumber': '本次入库数',
  'InStorage.productionDate': '生产日期',
  'InStorage.locationNo': '库位编号',
  'InStorage.advanceSaleSetting': '预售设置',
  'InStorage.advanceSale': '预售商品',
  'InStorage.advanceSaleDay': '建议预售天数',
  'InStorage.advanceSaleQty': '建议预售数量',
  'InStorage.receiveTime': '到货时间',
  'InStorage.confirmIn': '确认入库',
  'InStorage.cancel': '取消',
  'InStorage.inStorageSuccess': '商品入库成功',
  'InStorage.exceedingMaximum': '入库数超出采购数',
  'InStorage.selectedInstorageGoods': '请最少选择一个商品入库',
  /* InStorage --end */

  /* WarehouseInventory --start*/
  'WarehouseInventory.keyword': '搜索商品名称/SKU编码',
  'WarehouseInventory.product': '商品',
  'WarehouseInventory.skuInfo': '商品规格',
  'WarehouseInventory.noSku': '无规格',
  'WarehouseInventory.skuCode': 'SKU编码',
  'WarehouseInventory.warehouse': '所属仓库',
  'WarehouseInventory.inventory': '库存总量',
  'WarehouseInventory.defaultWarehouse': '全部仓库',
  /* WarehouseInventory --end */

  /* AddNewOutbound --start */
  'AddNewOutbound.outWarehouseNo': '出库单号',
  'AddNewOutbound.outboundTime': '出库日期',
  'AddNewOutbound.remark': '备注信息',
  'AddNewOutbound.remarkPlaceholder': '请输入备注信息',

  'AddNewOutbound.outboundGoods': '出库商品清单',
  'AddNewOutbound.addGoods': '添加商品',
  'AddNewOutbound.Repo': '所属仓库',
  'AddNewOutbound.purchaseSumQuantity': '出库总数',
  'AddNewOutbound.goodsWeight': '商品毛重（KG）',

  'AddNewOutbound.goods': '商品',
  'AddNewOutbound.skuName': '商品规格',
  'AddNewOutbound.skuCode': 'SKU编码',
  'AddNewOutbound.quantity': '库存量',
  'AddNewOutbound.outboundNumber': '出库数量',
  'AddNewOutbound.operation': '操作',
  'AddNewOutbound.delete': '删除',
  'AddNewOutbound.quantityReqiured': '请填写数量',
  'AddNewOutbound.skuSelectReqiured': '请至少选择一个商品',
  'AddNewOutbound.createSuccess': '出库单创建成功',
  'AddNewOutbound.save': '保存',
  'AddNewOutbound.cancel': '取消',
  'AddNewOutbound.backtoPre': '返回上一页',
  'AddNewOutbound.quantityUpdate': '商品数量发生变化, 库存不足',
  /* AddNewOutbound --end */

  /* GoodsOutbound --start */
  'GoodsOutbound.outWarehouseNo': '出库单号',
  'GoodsOutbound.outWarehouseNoRequired': '请输入出库单号',
  'GoodsOutbound.createTime': '出库时间',
  'GoodsOutbound.warehouse': '所属仓库',
  'GoodsOutbound.outboundQuantity': '出库数量',
  'GoodsOutbound.remark': '备注信息',
  'GoodsOutbound.operation': '操作',
  'GoodsOutbound.detail': '详情',
  'GoodsOutbound.selectWarehouse': '选择仓库',
  'GoodsOutbound.confirm': '确定',
  'GoodsOutbound.cancel': '取消',
  'GoodsOutbound.outboundTime': '出库时间',
  'GoodsOutbound.addOutbound': '新建出库',
  /* GoodsOutbound --end */

  /* AddNewStockCount --start */
  'AddNewStockCount.verificationNo': '盘点单号',
  'AddNewStockCount.inventoryTime': '盘点日期',
  'AddNewStockCount.remark': '备注信息',
  'AddNewStockCount.status': '盘点状态',
  'AddNewStockCount.counted': '已盘点',
  'AddNewStockCount.notCounted': '未盘点',
  'AddNewStockCount.remarkPlaceholder': '请输入备注信息',
  'AddNewStockCount.noRemark': '暂无',

  'AddNewStockCount.outboundGoods': '盘点商品清单',
  'AddNewStockCount.addGoods': '添加商品',
  'AddNewStockCount.Repo': '所属仓库',
  'AddNewStockCount.bookTotal': '账面总数',
  'AddNewStockCount.actualTotal': '实盘总数',

  'AddNewStockCount.goods': '商品',
  'AddNewStockCount.skuName': '商品规格',
  'AddNewStockCount.PONumber': '采购单号',
  'AddNewStockCount.inventory': '账面库存',
  'AddNewStockCount.locationNo': '库位编码',
  'AddNewStockCount.noLocationNo': '暂无',
  'AddNewStockCount.inventoryProfitAndLoss': '盘点盈亏',
  'AddNewStockCount.operation': '操作',
  'AddNewStockCount.delete': '删除',
  'AddNewStockCount.quantityReqiured': '请填写数量',
  'AddNewStockCount.skuSelectReqiured': '请至少选择一个商品',
  'AddNewStockCount.createSuccess': '盘点单创建成功',
  'AddNewStockCount.inventorySuccess': '盘点成功',
  'AddNewStockCount.save': '保存',
  'AddNewStockCount.cancel': '取消',
  'AddNewStockCount.backtoPre': '返回上一页',
  /* AddNewStockCount --end */

  /* StockCount --start */
  'StockCount.verificationNo': '盘点单号',
  'StockCount.verificationNoRequired': '请输入盘点单号',
  'StockCount.inventoryTime': '盘点时间',
  'StockCount.createTime': '盘点时间',
  'StockCount.warehouse': '所属仓库',
  'StockCount.bookTotal': '账面总数',
  'StockCount.actualTotal': '实盘总数',
  'StockCount.remark': '备注信息',
  'StockCount.counted': '已盘点',
  'StockCount.notCounted': '未盘点',
  'StockCount.status': '状态',
  'StockCount.operation': '操作',
  'StockCount.detail': '详情',
  'StockCount.inventory': '盘点',
  'StockCount.selectWarehouse': '选择仓库',
  'StockCount.confirm': '确定',
  'StockCount.cancel': '取消',
  'StockCount.countTime': '盘点时间',
  'StockCount.addStockCount': '新建盘点',
  /* StockCount --end */

  /* RichEditor --start */
  'RichEditor.previewArea': '预览区域',
  'RichEditor.goodsInfoPlace': '填写商品详情信息',
  'RichEditor.insertImage': '插入的图片',
  'RichEditor.title': '标题',
  'RichEditor.content': '正文',
  'RichEditor.uploadImage': '上传图片',
  /* RichEditor --end */
}
